name: e4l-frontend-staging

services:
  e4l-frontend-staging:
    restart: always
    image: ${CI_REGISTRY_IMAGE}:latest
    container_name: e4l-frontend-staging
    ports:
      - 8884:80
    volumes:
      - /opt/e4l-news:/usr/share/nginx/news
    environment:
      # - PUBLIC_PATH=/e4l
      - PUBLIC_PATH=
      # - API_URL=${STAGING_API_URL}
      - API_URL=http://localhost:8084/e4lapi
      - TZ=Europe/Luxembourg
