name: e4l-frontend-green-prod

services:
  e4l-frontend-green-prod:
    restart: always
    image: ${CI_REGISTRY_IMAGE}:release
    container_name: e4l-frontend-green-prod
    ports:
      - 8886:80
    volumes:
      - /opt/e4l-news-prod:/usr/share/nginx/news
    environment:
      - PUBLIC_PATH=
      - API_URL=${PROD_API_URL}
      - TZ=Europe/Luxembourg
    networks:
      - e4l-frontend-net-prod

networks:
  e4l-frontend-net-prod:
    external: false
    name: e4l-frontend-net-prod