name: e4l-nginx-frontend-prod

services:
  e4l-nginx-frontend-prod:
    image: nginx:1.28-alpine
    container_name: e4l-nginx-frontend-prod
    ports:
      - "8890:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - e4l-frontend-net-prod

networks:
  e4l-frontend-net-prod:
    external: true