services:
  gitlab:
    image: gitlab/gitlab-ce:18.4.5-ce.0
    container_name: gitlab
    restart: always
    hostname: 'localhost'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # CONFIG
        external_url 'http://localhost:8929'

        registry_external_url 'https://localhost:5050'
        gitlab_rails['registry_enabled'] = true
        registry_nginx['ssl_certificate'] = "/etc/gitlab/ssl/localhost.crt"
        registry_nginx['ssl_certificate_key'] = "/etc/gitlab/ssl/localhost.key"
        registry_nginx['listen_https'] = true
        registry_nginx['listen_port'] = 5050
        
        # OPTIMIZATIONS
        puma['worker_processes'] = 0
        sidekiq['concurrency'] = 10
        prometheus_monitoring['enable'] = false
    ports:
      - '8929:8929'
      - '5050:5050'
      - '2224:22'
    volumes:
      - './config:/etc/gitlab'
      - './logs:/var/log/gitlab'
      - './data:/var/opt/gitlab'
    shm_size: '256m'
